"""Add job table

Revision ID: 237e54a07ce1
Revises: 41988c8fd267
Create Date: 2025-08-21 19:56:37.845676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '237e54a07ce1'
down_revision = '41988c8fd267'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('company', sa.String(length=150), nullable=False),
    sa.Column('location', sa.String(length=150), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job')
    # ### end Alembic commands ###
