name: Run Daily Job Scraper

on:
  schedule:
    # Runs at midnight UTC every day
    - cron: '0 0 * * *'
  workflow_dispatch: # Allows you to run it manually

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run scraper
      env:
        # Use the secret we just created
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
      run: python3 scraper.py